// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/db/proto/debug.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	data/db/proto/debug.proto
	data/db/proto/hub.proto
	data/db/proto/lock.proto
	data/db/proto/pointers.proto
	data/db/proto/recipes.proto

It has these top-level messages:
	DebugPtrsRequest
	DebugPtrsReply
	CreateSnapshotWrite
	SetPointerWrite
	AcquirePointerWrite
	Write
	RegisterClientRequest
	RegisterClientReply
	WriteManyRequest
	WriteManyReply
	HeadManyRequest
	HeadManyStreamReply
	AllPathsToSnapshotRequest
	AllPathsToSnapshotReply
	HasSnapshotsRequest
	HasSnapshotsReply
	IsHoldingPointerRequest
	IsHoldingPointerReply
	PointerAtRev
	PointerAtSnapshot
	PointerMetadata
	GetRequest
	GetReply
	AcquirePointerRequest
	AcquirePointerReply
	PointerMetadataRequest
	PointerMetadataReply
	RecipeRTag
	RecipeWTag
	LookupPathToSnapshotRequest
	LookupPathToSnapshotReply
	StoredRecipe
	Recipe
	Path
	WriteFileOp
	EditFileOp
	EditFileSplice
	InsertBytesFileOp
	DeleteBytesFileOp
	RemoveFileOp
	ChmodFileOp
	RmdirOp
	SubdirOp
	DirOp
	PreserveOp
	IdentityOp
	OverlayOp
	FailureOp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DebugPtrsRequest struct {
	Types []string `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
	// The username
	DEPRECATEDOwner string `protobuf:"bytes,2,opt,name=DEPRECATED_owner,json=DEPRECATEDOwner" json:"DEPRECATED_owner,omitempty"`
	// The user id
	OwnerId uint64 `protobuf:"varint,3,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
}

func (m *DebugPtrsRequest) Reset()                    { *m = DebugPtrsRequest{} }
func (m *DebugPtrsRequest) String() string            { return proto1.CompactTextString(m) }
func (*DebugPtrsRequest) ProtoMessage()               {}
func (*DebugPtrsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DebugPtrsRequest) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *DebugPtrsRequest) GetDEPRECATEDOwner() string {
	if m != nil {
		return m.DEPRECATEDOwner
	}
	return ""
}

func (m *DebugPtrsRequest) GetOwnerId() uint64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type DebugPtrsReply struct {
	PtrIds []string `protobuf:"bytes,1,rep,name=ptr_ids,json=ptrIds" json:"ptr_ids,omitempty"`
}

func (m *DebugPtrsReply) Reset()                    { *m = DebugPtrsReply{} }
func (m *DebugPtrsReply) String() string            { return proto1.CompactTextString(m) }
func (*DebugPtrsReply) ProtoMessage()               {}
func (*DebugPtrsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DebugPtrsReply) GetPtrIds() []string {
	if m != nil {
		return m.PtrIds
	}
	return nil
}

func init() {
	proto1.RegisterType((*DebugPtrsRequest)(nil), "wm.data.db.DebugPtrsRequest")
	proto1.RegisterType((*DebugPtrsReply)(nil), "wm.data.db.DebugPtrsReply")
}

func init() { proto1.RegisterFile("data/db/proto/debug.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x49, 0x2c, 0x49,
	0xd4, 0x4f, 0x49, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x49, 0x4d, 0x2a, 0x4d, 0xd7,
	0x03, 0xb3, 0x85, 0xb8, 0xca, 0x73, 0xf5, 0x40, 0xb2, 0x7a, 0x29, 0x49, 0x4a, 0x79, 0x5c, 0x02,
	0x2e, 0x20, 0xa9, 0x80, 0x92, 0xa2, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11,
	0x2e, 0xd6, 0x92, 0xca, 0x82, 0xd4, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x08, 0x47,
	0x48, 0x93, 0x4b, 0xc0, 0xc5, 0x35, 0x20, 0xc8, 0xd5, 0xd9, 0x31, 0xc4, 0xd5, 0x25, 0x3e, 0xbf,
	0x3c, 0x2f, 0xb5, 0x48, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x88, 0x1f, 0x21, 0xee, 0x0f, 0x12,
	0x16, 0x92, 0xe4, 0xe2, 0x00, 0xcb, 0xc7, 0x67, 0xa6, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0xb0, 0x04,
	0xb1, 0x83, 0xf9, 0x9e, 0x29, 0x4a, 0x9a, 0x5c, 0x7c, 0x48, 0xf6, 0x15, 0xe4, 0x54, 0x0a, 0x89,
	0x73, 0xb1, 0x17, 0x94, 0x80, 0x94, 0xc2, 0xec, 0x63, 0x2b, 0x28, 0x29, 0xf2, 0x4c, 0x29, 0x76,
	0x32, 0x8c, 0xd2, 0x4f, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0xcf,
	0xcc, 0x4b, 0xc9, 0xcd, 0xcc, 0xc9, 0x49, 0xcd, 0x4b, 0xd7, 0xcf, 0xcd, 0x2c, 0xce, 0xd0, 0x47,
	0xf1, 0x9f, 0x35, 0x98, 0x4c, 0x62, 0x03, 0x53, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77,
	0x86, 0x07, 0xf1, 0xfd, 0x00, 0x00, 0x00,
}
