// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/db/proto/pointers.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ptrs
type PointerAtRev struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Rev int64  `protobuf:"varint,2,opt,name=rev" json:"rev,omitempty"`
}

func (m *PointerAtRev) Reset()                    { *m = PointerAtRev{} }
func (m *PointerAtRev) String() string            { return proto1.CompactTextString(m) }
func (*PointerAtRev) ProtoMessage()               {}
func (*PointerAtRev) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *PointerAtRev) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PointerAtRev) GetRev() int64 {
	if m != nil {
		return m.Rev
	}
	return 0
}

type PointerAtSnapshot struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Rev         int64  `protobuf:"varint,2,opt,name=rev" json:"rev,omitempty"`
	SnapId      string `protobuf:"bytes,3,opt,name=snap_id,json=snapId" json:"snap_id,omitempty"`
	UpdatedAtNs int64  `protobuf:"varint,4,opt,name=updated_at_ns,json=updatedAtNs" json:"updated_at_ns,omitempty"`
	Frozen      bool   `protobuf:"varint,5,opt,name=frozen" json:"frozen,omitempty"`
}

func (m *PointerAtSnapshot) Reset()                    { *m = PointerAtSnapshot{} }
func (m *PointerAtSnapshot) String() string            { return proto1.CompactTextString(m) }
func (*PointerAtSnapshot) ProtoMessage()               {}
func (*PointerAtSnapshot) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *PointerAtSnapshot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PointerAtSnapshot) GetRev() int64 {
	if m != nil {
		return m.Rev
	}
	return 0
}

func (m *PointerAtSnapshot) GetSnapId() string {
	if m != nil {
		return m.SnapId
	}
	return ""
}

func (m *PointerAtSnapshot) GetUpdatedAtNs() int64 {
	if m != nil {
		return m.UpdatedAtNs
	}
	return 0
}

func (m *PointerAtSnapshot) GetFrozen() bool {
	if m != nil {
		return m.Frozen
	}
	return false
}

type PointerMetadata struct {
	// The host that currently has the write lock.
	WriteHost string `protobuf:"bytes,1,opt,name=write_host,json=writeHost" json:"write_host,omitempty"`
}

func (m *PointerMetadata) Reset()                    { *m = PointerMetadata{} }
func (m *PointerMetadata) String() string            { return proto1.CompactTextString(m) }
func (*PointerMetadata) ProtoMessage()               {}
func (*PointerMetadata) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *PointerMetadata) GetWriteHost() string {
	if m != nil {
		return m.WriteHost
	}
	return ""
}

// ptrs get
type GetRequest struct {
	At *PointerAtRev `protobuf:"bytes,1,opt,name=at" json:"at,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *GetRequest) GetAt() *PointerAtRev {
	if m != nil {
		return m.At
	}
	return nil
}

type GetReply struct {
	SnapId    string             `protobuf:"bytes,1,opt,name=snap_id,json=snapId" json:"snap_id,omitempty"`
	PtrAtSnap *PointerAtSnapshot `protobuf:"bytes,2,opt,name=ptr_at_snap,json=ptrAtSnap" json:"ptr_at_snap,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto1.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *GetReply) GetSnapId() string {
	if m != nil {
		return m.SnapId
	}
	return ""
}

func (m *GetReply) GetPtrAtSnap() *PointerAtSnapshot {
	if m != nil {
		return m.PtrAtSnap
	}
	return nil
}

// ptrs acquire
type AcquirePointerRequest struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	WriteHost string `protobuf:"bytes,2,opt,name=write_host,json=writeHost" json:"write_host,omitempty"`
}

func (m *AcquirePointerRequest) Reset()                    { *m = AcquirePointerRequest{} }
func (m *AcquirePointerRequest) String() string            { return proto1.CompactTextString(m) }
func (*AcquirePointerRequest) ProtoMessage()               {}
func (*AcquirePointerRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *AcquirePointerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AcquirePointerRequest) GetWriteHost() string {
	if m != nil {
		return m.WriteHost
	}
	return ""
}

type AcquirePointerReply struct {
	PtrAtRev *PointerAtRev `protobuf:"bytes,1,opt,name=ptr_at_rev,json=ptrAtRev" json:"ptr_at_rev,omitempty"`
}

func (m *AcquirePointerReply) Reset()                    { *m = AcquirePointerReply{} }
func (m *AcquirePointerReply) String() string            { return proto1.CompactTextString(m) }
func (*AcquirePointerReply) ProtoMessage()               {}
func (*AcquirePointerReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *AcquirePointerReply) GetPtrAtRev() *PointerAtRev {
	if m != nil {
		return m.PtrAtRev
	}
	return nil
}

type PointerMetadataRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *PointerMetadataRequest) Reset()                    { *m = PointerMetadataRequest{} }
func (m *PointerMetadataRequest) String() string            { return proto1.CompactTextString(m) }
func (*PointerMetadataRequest) ProtoMessage()               {}
func (*PointerMetadataRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *PointerMetadataRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PointerMetadataReply struct {
	Metadata *PointerMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *PointerMetadataReply) Reset()                    { *m = PointerMetadataReply{} }
func (m *PointerMetadataReply) String() string            { return proto1.CompactTextString(m) }
func (*PointerMetadataReply) ProtoMessage()               {}
func (*PointerMetadataReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *PointerMetadataReply) GetMetadata() *PointerMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto1.RegisterType((*PointerAtRev)(nil), "wm.data.db.PointerAtRev")
	proto1.RegisterType((*PointerAtSnapshot)(nil), "wm.data.db.PointerAtSnapshot")
	proto1.RegisterType((*PointerMetadata)(nil), "wm.data.db.PointerMetadata")
	proto1.RegisterType((*GetRequest)(nil), "wm.data.db.GetRequest")
	proto1.RegisterType((*GetReply)(nil), "wm.data.db.GetReply")
	proto1.RegisterType((*AcquirePointerRequest)(nil), "wm.data.db.AcquirePointerRequest")
	proto1.RegisterType((*AcquirePointerReply)(nil), "wm.data.db.AcquirePointerReply")
	proto1.RegisterType((*PointerMetadataRequest)(nil), "wm.data.db.PointerMetadataRequest")
	proto1.RegisterType((*PointerMetadataReply)(nil), "wm.data.db.PointerMetadataReply")
}

func init() { proto1.RegisterFile("data/db/proto/pointers.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0x54, 0x52, 0x28, 0xe9, 0x0b, 0x9f, 0x06, 0x96, 0x48, 0xb0, 0x52, 0xe5, 0x53, 0x4e, 0xc9,
	0xb2, 0x48, 0xcb, 0x01, 0x71, 0x28, 0x07, 0x3e, 0x0e, 0x0b, 0xc8, 0xdc, 0xb8, 0x44, 0xce, 0xda,
	0x6c, 0x2c, 0x35, 0xb1, 0x37, 0x7e, 0x69, 0x05, 0x3f, 0x81, 0x5f, 0x8d, 0xec, 0xf5, 0x96, 0x36,
	0x14, 0xf5, 0x92, 0xe4, 0x4d, 0x66, 0xfc, 0x66, 0x26, 0x81, 0x17, 0x82, 0x23, 0x2f, 0x45, 0x5d,
	0x9a, 0x5e, 0xa3, 0x2e, 0x8d, 0x56, 0x1d, 0xca, 0xde, 0x16, 0x7e, 0x24, 0xb0, 0x6e, 0x0b, 0x47,
	0x28, 0x44, 0x4d, 0x4f, 0xe0, 0xee, 0xd7, 0xeb, 0xb7, 0x0b, 0x64, 0x72, 0x45, 0xee, 0x43, 0xac,
	0x44, 0x16, 0xcd, 0xa3, 0x7c, 0xc6, 0x62, 0x25, 0xc8, 0x43, 0x98, 0xf4, 0x72, 0x95, 0xc5, 0xf3,
	0x28, 0x9f, 0x30, 0xf7, 0x48, 0x7f, 0x47, 0xf0, 0x68, 0x23, 0xf9, 0xd6, 0x71, 0x63, 0x1b, 0x8d,
	0x87, 0x75, 0xe4, 0x19, 0xdc, 0xb1, 0x1d, 0x37, 0x95, 0x12, 0xd9, 0xc4, 0xd3, 0xa6, 0x6e, 0xfc,
	0x24, 0x08, 0x85, 0x7b, 0x83, 0x11, 0x1c, 0xa5, 0xa8, 0x38, 0x56, 0x9d, 0xcd, 0x6e, 0x79, 0x51,
	0x1a, 0xc0, 0x05, 0x7e, 0xb6, 0xe4, 0x08, 0xa6, 0x3f, 0x7a, 0xfd, 0x4b, 0x76, 0xd9, 0xed, 0x79,
	0x94, 0x27, 0x2c, 0x4c, 0xf4, 0x04, 0x1e, 0x04, 0x2f, 0xe7, 0x12, 0xb9, 0x0b, 0x45, 0x8e, 0x01,
	0xd6, 0xbd, 0x42, 0x59, 0x35, 0xda, 0x62, 0x70, 0x34, 0xf3, 0xc8, 0x47, 0x6d, 0x91, 0x9e, 0x01,
	0x7c, 0x90, 0xc8, 0xe4, 0xd5, 0x20, 0x2d, 0x92, 0x1c, 0x62, 0x7e, 0x4d, 0x4a, 0x4f, 0xb3, 0xe2,
	0x6f, 0x2f, 0xc5, 0x76, 0x29, 0x2c, 0xe6, 0x48, 0x6b, 0x48, 0xbc, 0xce, 0x2c, 0x7f, 0x6e, 0x47,
	0x89, 0x76, 0xa2, 0xbc, 0x85, 0xd4, 0x60, 0xef, 0x62, 0x38, 0xc0, 0xa7, 0x4f, 0x4f, 0x8f, 0xf7,
	0x9e, 0x7b, 0xd3, 0x1c, 0x9b, 0x19, 0x0c, 0x23, 0x7d, 0x0f, 0x4f, 0x17, 0x17, 0x57, 0x83, 0xea,
	0x65, 0xa0, 0xdd, 0xd8, 0x1c, 0xb7, 0xbb, 0x9b, 0x31, 0x1e, 0x67, 0x3c, 0x87, 0xc7, 0xe3, 0x73,
	0x9c, 0xed, 0x33, 0x80, 0xe0, 0xce, 0x7d, 0x9a, 0x43, 0xa1, 0x13, 0xef, 0x8b, 0xc9, 0x15, 0xcd,
	0xe1, 0x68, 0x54, 0xf2, 0x7f, 0x7c, 0xd1, 0x2f, 0xf0, 0xe4, 0x1f, 0xa6, 0xdb, 0xfc, 0x1a, 0x92,
	0x36, 0x00, 0x61, 0xef, 0xf3, 0x3d, 0x7b, 0x37, 0x9a, 0x0d, 0xf9, 0xdd, 0xcb, 0xef, 0xe5, 0xa5,
	0xc2, 0x66, 0xa8, 0x8b, 0x0b, 0xdd, 0x96, 0x6b, 0xd5, 0x89, 0x56, 0x2d, 0x97, 0xb2, 0xbb, 0x2c,
	0x5b, 0x65, 0x9b, 0x72, 0xe7, 0x37, 0x7f, 0xe3, 0xaf, 0xf5, 0xd4, 0xdf, 0x5e, 0xfd, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xa1, 0x89, 0xf0, 0x30, 0x04, 0x03, 0x00, 0x00,
}
