// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bridge/fs/proto/config.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	bridge/fs/proto/config.proto
	bridge/fs/proto/fs.proto
	bridge/fs/proto/state.proto

It has these top-level messages:
	SnapshotConfig
	SnapshotDirRequest
	SnapshotDirReply
	CheckoutStatus
	CheckoutRequest
	CheckoutReply
	ResetCheckoutRequest
	ResetCheckoutReply
	WM2FSStartRequest
	WM2FSStartReply
	WM2FSStopRequest
	WM2FSStopReply
	FS2WMStartRequest
	FS2WMStartReply
	FS2WMStatusRequest
	FS2WMStatusReply
	FS2WMPointerStatusRequest
	FS2WMPointerStatusReply
	FS2WMFSyncRequest
	FS2WMFSyncReply
	FS2WMStopRequest
	FS2WMStopReply
	FsBridgeState
	FsToWmState
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wm_data "github.com/windmilleng/mish/data/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Configuration for runners and compositions that need to capture file system state.
type SnapshotConfig struct {
	Matcher *wm_data.Matcher `protobuf:"bytes,1,opt,name=matcher" json:"matcher,omitempty"`
}

func (m *SnapshotConfig) Reset()                    { *m = SnapshotConfig{} }
func (m *SnapshotConfig) String() string            { return proto1.CompactTextString(m) }
func (*SnapshotConfig) ProtoMessage()               {}
func (*SnapshotConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SnapshotConfig) GetMatcher() *wm_data.Matcher {
	if m != nil {
		return m.Matcher
	}
	return nil
}

func init() {
	proto1.RegisterType((*SnapshotConfig)(nil), "wm.fs.SnapshotConfig")
}

func init() { proto1.RegisterFile("bridge/fs/proto/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2a, 0xca, 0x4c,
	0x49, 0x4f, 0xd5, 0x4f, 0x2b, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x03, 0x73, 0x84, 0x58, 0xcb, 0x73, 0xf5, 0xd2, 0x8a, 0xa5, 0x24, 0x52, 0x12,
	0x4b, 0x12, 0xa1, 0xf2, 0xb9, 0x89, 0x25, 0xc9, 0x19, 0xa9, 0x45, 0x10, 0x05, 0x4a, 0x36, 0x5c,
	0x7c, 0xc1, 0x79, 0x89, 0x05, 0xc5, 0x19, 0xf9, 0x25, 0xce, 0x60, 0x8d, 0x42, 0x5a, 0x5c, 0xec,
	0x50, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x02, 0x7a, 0xe5, 0xb9, 0x7a, 0x20, 0x03,
	0xf4, 0x7c, 0x21, 0xe2, 0x41, 0x30, 0x05, 0x4e, 0xc6, 0x51, 0x86, 0xe9, 0x99, 0x25, 0x19, 0xa5,
	0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xe5, 0x99, 0x79, 0x29, 0xb9, 0x99, 0x39, 0x39, 0xa9, 0x79,
	0xe9, 0xfa, 0xb9, 0x99, 0xc5, 0x19, 0xfa, 0x68, 0x4e, 0xb3, 0x06, 0x93, 0x49, 0x6c, 0x60, 0xca,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xfb, 0x68, 0x8a, 0xba, 0x00, 0x00, 0x00,
}
